name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: actions/checkout@v3

      - run: npm i -g pnpm

      - run: pnpm install

      - run: pnpm test -- --coverage

      - uses: codecov/codecov-action@v3
