name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 17

      - uses: actions/checkout@v2

      - run: npm i -g pnpm

      - run: pnpm install

      - run: pnpm test -- --coverage

      - uses: codecov/codecov-action@v2
